# Generated by Django 4.2.4 on 2024-04-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_management', '0004_alter_estudiante_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='direccion_notas',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='direccion_psico',
            field=models.CharField(default='', max_length=255),
        ),
    ]
