# Generated by Django 4.2.4 on 2024-04-03 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_management', '0005_estudiante_direccion_notas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='direccion_notas',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='direccion_psico',
        ),
    ]
